name: PostmanTestsWorkflow_Docker

#Trigger
on: 
  push:
    branches:
      - main
#Response
jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout Code
        
      - name: Postman Scripts Run
        id: run-newman
        run: docker-compose up    

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
