version: '3.9'

networks:
    quick_app:
      name: quicknetwork
      driver: bridge

services:
    postman:
        container_name: postmanTests
        build:
            context: ./QuickRestaurant.QA.Tests/postman
            dockerfile: Dockerfile
        image: quickrestaurant_postman_tests
        command:
                run DummyPostmanCollection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html  > testResults/runreport1.html
        volumes:
            - ./QuickRestaurant.QA.Tests/postman:/etc/newman
        networks: 
            - quick_app


volumes:
    local_admindb_volume: {}    
    local_coredb_volume: {}
