# Workflow
name: PostmanTestsWorkflow_FailingTests

#Triggers
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

#Response
jobs:
 Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout code
      # Install Node on the runner
      - name: Install Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '16.x'
    
    # Install the newman command line utility and also install the html extra reporter
      - name: Install newman and the HTML reporting add-on
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


    # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: >
          newman run ./QuickRestaurant.QA.Tests/postman/QSRPostmanTests.json
          --env-var coreapiurl=alpha.qsr.world/api/v1
          -r cli,htmlextra --reporter-htmlextra-export ./QuickRestaurant.QA.Tests/postman/reports/TestsReport.html
        
    # Upload the contents of Test Results directory to workspace
      - name: Upload run results
        uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: SmokeTestReports
          path: testArtifacts

 LoadTestWithK6:
  runs-on: ubuntu-latest
  needs: Run_Postman_Scripts
  steps:
  - uses: actions/checkout@v2.3.4
    name: Checkout code
  - name: Run K6 script
    uses: k6io/action@v0.1
    with:
      filename: ./QuickRestaurant.QA.Tests/performance/HealthCheck/LoadTest.js
    env:
      QSR__API_BASEURL: alpha.qsr.world/api/v1
     
