# Workflow
name: NewmanActionWorkflow

#Triggers
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

#Response
jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout code
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: ./QuickRestaurant.QA.Tests/postman/AWSTests.json
          environment: TestEnvironment.json
          reporters: cli
