# This is a basic workflow that is manually triggered

name: PostmanTestsWorkflow

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Postman Scripts Run
        id: run-newman
        run: docker-compose up     
      - name: Output the run Details
        #uses: actions/upload-artifact@v2.2.4
        uses: ishworkh/docker-image-artifact-upload@v1
        with: 
          name: RunReports
          path: testResults
      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
