# This is a basic workflow that is manually triggered

name: PostmanTestsWorkflow

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Postman Scripts Run
        run: docker-compose up     
      - name: Output the run Details
        uses: actions/upload-artifact@v2           
        with: 
          name: RunReports
          path: testResults
