# This is a basic workflow that is manually triggered

name: PostmanTestsWorkflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

jobs:
  - name: test
    run: docker-compose up
