# This is a basic workflow that is manually triggered

name: PostmanTestsWorkflow

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Postman Scripts Run
        run: docker-compose up
        
      - name: Output the run Details
      - uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: Reports
