# This is a basic workflow that is manually triggered

name: PostmanTestsWorkflow

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: docker-compose up
