# Workflow
name: SecretsTestWorkflow

#Triggers
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

#Response
jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
     - name: Step 1 - Echo out a GitHub Actions Secret to the logs
       run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.MYSECRET }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.MYSECRET}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
     - name: Step 2 - GitHub Action if statement (true)
       env: 
          WHO_TO_TRUST: ${{ secrets.MYSECRET }}
       if:  env.WHO_TO_TRUST == 'TrustNo1'
       run: echo "I know what the secret token is!"

      # A GitHub Actions if statement with a secret environment variable
     - name: Step 3 - Conditional GitHub Action (false)
       shell: bash
       env: 
          WHO_TO_TRUST: ${{ secrets.MYSECRET }}
       if:  env.WHO_TO_TRUST != 'TrustNobody'
       run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"

