# Workflow
name: PostmanTestsWorkflow

#Triggers
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

#Response
jobs:
  Run_Postman_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout code
      # Install Node on the runner
      - name: Install Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '16.x'
    
    # Install the newman command line utility and also install the html extra reporter
      - name: Install newman and the HTML reporting add-on
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

    # Make directory to upload the test results
      - name: Make Directory to upload test results
        run: mkdir -p testArtifacts

    # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: >
          newman run ./QuickRestaurant.QA.Tests/EcommGraphQL.json --env-var "AdminUI_Client_Secret=4b47Q~Lnsn-y6LyfWJW.f88.QAPN4y5sYkABH" --env-var "AdminUI_Client_Id=3337a4dc-170d-42d2-b3a3-ce0294337358" -e ./QuickRestaurant.QA.Tests/Localhost.postman_environment.json -g ./QuickRestaurant.QA.Tests/globalsfile.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/TestsReport.html
  
  # Upload the contents of Test Results directory to workspace
      - name: Upload run results
        uses: actions/upload-artifact@v2
        with: 
          name: SmokeTestReports
          path: testArtifacts

